In [3]:
import pandas as pd

In [4]:
# read csv file 
df=pd.read_csv("customer_data.csv")

In [5]:
df.shape

(50, 16)

In [6]:
df.head()

,customer_id,customer_name,age,gender,region,signup_date,last_purchase_date,total_purchases,total_spend,avg_order_value,product_category,email_opens,email_clicks,loyalty_tier,days_since_last_purchase,churn_risk
0,C001,James Anderson,34,Male,Northeast,2021-03-15,2024-11-20,18,1240.50,68.92,Electronics,45,12,Gold,40,Low
1,C002,Maria Garcia,27,Female,Southwest,2022-07-01,2024-12-10,7,430.00,61.43,Clothing,22,5,Silver,20,Low
2,C003,Robert Brown,52,Male,Midwest,2020-01-10,2024-09-05,32,4875.00,152.34,Home & Garden,80,30,Platinum,116,Medium
3,C004,Linda Davis,41,Female,Southeast,2021-11-22,2024-08-01,10,610.75,61.08,Beauty,18,3,Silver,152,High
4,C005,Michael Wilson,29,Male,West,2023-02-14,2024-12-28,4,189.00,47.25,Books,10,2,Bronze,3,Low

In [7]:
df.describe()

,age,total_purchases,total_spend,avg_order_value,email_opens,email_clicks,days_since_last_purchase
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,39.260000,19.700000,2473.865000,91.473800,43.160000,14.920000,86.920000
std,11.115002,15.878685,2933.987688,44.796377,31.236007,13.820777,75.782406
min,22.000000,2.000000,98.000000,43.330000,6.000000,1.000000,1.000000
25%,30.000000,7.000000,400.000000,56.157500,16.500000,4.000000,19.250000
50%,38.000000,15.000000,1010.000000,65.315000,32.500000,9.000000,64.500000
75%,47.750000,27.250000,3287.500000,121.722500,68.750000,24.250000,148.500000
max,62.000000,60.000000,10200.000000,175.000000,100.000000,45.000000,265.000000

In [8]:
df.dtypes

customer_id                  object
customer_name                object
age                           int64
gender                       object
region                       object
signup_date                  object
last_purchase_date           object
total_purchases               int64
total_spend                 float64
avg_order_value             float64
product_category             object
email_opens                   int64
email_clicks                  int64
loyalty_tier                 object
days_since_last_purchase      int64
churn_risk                   object
dtype: object

In [9]:
#Check missing values:
df.isnull().sum()

customer_id                 0
customer_name               0
age                         0
gender                      0
region                      0
signup_date                 0
last_purchase_date          0
total_purchases             0
total_spend                 0
avg_order_value             0
product_category            0
email_opens                 0
email_clicks                0
loyalty_tier                0
days_since_last_purchase    0
churn_risk                  0
dtype: int64

In [10]:
#Check duplicate rows
df.duplicated().sum()

0

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
#changing date format from object to datetime

df["signup_date"]= pd.to_datetime(df["signup_date"])
df["last_purchase_date"] = pd.to_datetime(df["last_purchase_date"])

In [13]:
#remove extra white spaces and generalizing the columns

df["gender"]           = df["gender"].str.strip().str.title()
df["region"]           = df["region"].str.strip().str.title()
df["product_category"] = df["product_category"].str.strip().str.title()
df["loyalty_tier"]     = df["loyalty_tier"].str.strip().str.title()
df["churn_risk"]       = df["churn_risk"].str.strip().str.title()

In [14]:
#datatypes after cleaning
df.dtypes

customer_id                         object
customer_name                       object
age                                  int64
gender                              object
region                              object
signup_date                 datetime64[ns]
last_purchase_date          datetime64[ns]
total_purchases                      int64
total_spend                        float64
avg_order_value                    float64
product_category                    object
email_opens                          int64
email_clicks                         int64
loyalty_tier                        object
days_since_last_purchase             int64
churn_risk                          object
dtype: object

In [15]:
df.describe()

,age,signup_date,last_purchase_date,total_purchases,total_spend,avg_order_value,email_opens,email_clicks,days_since_last_purchase
count,50.000000,50,50,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,39.260000,2021-05-24 21:36:00,2024-10-05 00:28:48,19.700000,2473.865000,91.473800,43.160000,14.920000,86.920000
min,22.000000,2018-02-09 00:00:00,2024-04-10 00:00:00,2.000000,98.000000,43.330000,6.000000,1.000000,1.000000
25%,30.000000,2020-02-24 00:00:00,2024-08-04 12:00:00,7.000000,400.000000,56.157500,16.500000,4.000000,19.250000
50%,38.000000,2021-04-26 00:00:00,2024-10-27 12:00:00,15.000000,1010.000000,65.315000,32.500000,9.000000,64.500000
75%,47.750000,2022-12-15 00:00:00,2024-12-11 12:00:00,27.250000,3287.500000,121.722500,68.750000,24.250000,148.500000
max,62.000000,2023-11-01 00:00:00,2024-12-30 00:00:00,60.000000,10200.000000,175.000000,100.000000,45.000000,265.000000
std,11.115002,NaN,NaN,15.878685,2933.987688,44.796377,31.236007,13.820777,75.782406

In [16]:
df.to_csv("clean_customer_data.csv", index=False)